### ISSUE TITLE
how we can implement FreeRadius-mongodb in opnwrt ? 

### ISSUE THREAD

**Issue by Krunalvaghasiya** [intersvyaz/freeradius-mongodb#1]
Hi 

We are using coovachilli into opnwrt & there is requirement to integrete freeradius service. & we want our backend in our mongodb.. Can you tell me your these current development working fine ? if yes then can you tell me how may i use these in opnwrt.

**Comment by gureedo** [comment]
Hi, we use this module in production.
I don't know how to build packages for openwrt, but I can say how to build freeradius with this module from sources.
* Download freeradius sources from `ftp://ftp.freeradius.org/pub/radius/`;
* Clone this module source into `<freeradius_sources>/src/modules/rlm_mongodb`.
* Add `rlm_mongodb` line to `<freeradius_sources>/src/modules/stable` file.
* `./configure && make`
* Profit!
